import Redis from 'ioredis';
import { config } from '../config/index.js';
import { logger } from './logger.js';

// Lazily-initialized shared Redis client. Returns null when REDIS_URL is not
// configured, so callers can fall back to in-memory implementations (single
// instance deployments). The connection is created on first use and failures
// are logged but never thrown, to avoid crashing the process over Redis.
let client: Redis | null = null;
let initialized = false;

export function getRedis(): Redis | null {\n  if (initialized) return client;\n  initialized = true;\n\n  if (!config.redis.url) {\n    if (config.isProduction) {\n      logger.warn(\n        'REDIS_URL is not set in production — cross-instance webhook idempotency and rate limits are DISABLED. ' +\n          'Set REDIS_URL to enable safe horizontal scaling.'\n      );\n    }\n    return null;\n  }\n\n  try {\n    // Upstash and most managed Redis providers require TLS (rediss://).\n    // Auto-upgrade plain redis:// URLs that point to upstash.io or render.com\n    // to avoid \"Connection closed\" after the first idle timeout.\n    let url = config.redis.url;\n    if (url.startsWith('redis://') && (url.includes('upstash.io') || url.includes('render.com'))) {\n      url = url.replace('redis://', 'rediss://');\n      logger.info('Auto-upgraded Redis URL to TLS (rediss://) for managed provider');\n    }\n    client = new Redis(url, {\n      maxRetriesPerRequest: 2,\n      lazyConnect: true,\n      connectTimeout: 10000,\n      retryStrategy: (times) => {\n        if (times > 5) return null;\n        return Math.min(times * 500, 3000);\n      },\n    });\n    client.setMaxListeners(20);\n    client.on('error', (err) => logger.debug({ err: err.message }, 'Redis client error'));\n  } catch (err) {\n    logger.warn({ err: (err as Error).message }, 'Failed to initialize Redis client');\n    client = null;\n  }\n\n  return client;\n}\n\nexport async function closeRedis(): Promise<void> {\n  if (client) {\n    try {\n      await client.quit();\n    } catch (err) {\n      logger.warn({ err: (err as Error).message }, 'Error closing Redis connection');\n    }\n    client = null;\n  }\n  initialized = false;\n}\n